### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by rgaiacs** [annakrystalli/RSE-Sheffield.github.io#2]
You can apply [hacktoberfest-patch-1.txt](https://github.com/annakrystalli/RSE-Sheffield.github.io/files/1437850/hacktoberfest-patch-1.txt) to fix some typos.

# Feedback to #4b2f0cd

Overall, the blog post is great. Some suggestions:

- [x] How many people attended the kick off meetup?
- [x] From those that attended the kick off meetup, how many have submitted a pull request to a project that isn't their own or close-related to work (if you work on project X, pull requests not to X).
- [x] Re-write

  > As for me, well I'll be honest, my t-shirt was mainly earned by helping with typos! Sadly the main thing I worked on over the session for a variety did not end up making the cut to submit as a functional PR. Instead there'll be a personal blog about the experience, coming soon. Mostly however **I loved the experience and already looking forward to organising it next year!**

  with

  > My t-shirt was mainly earned by helping with typos. In Hackoberfest, the size of your contribution doesn't matter as long as you send a contribution. And find typos is very hard and time consuming due our brain auto-correct feature. Sadly, the coding pieces that I worked on over the session did not end up making the cut to submit as a functional PR **yet**. Mostly however **I loved the experience and already looking forward to organising it next year!**
  >
  > P.S.: There'll be a personal blog about my experience during Hacktoberfest soon.

  This is only a matter of how to write and invite people to participate. I'm trying to make appealing for "first-time contributors" to show up in 2018 even if they only want to read some documentation and have help to send pull request to fix typos.
- [x] Can you include three things that you plan to do different in 2018? This will make your blog post shy.

**Comment by annakrystalli** [comment]
Thanks for the super useful feedback @rgaiacs! 🙏

**Comment by annakrystalli** [comment]
Hey @rgaiacs. Updated with your suggestions. planning to make a PR soon. Happy to recieve any comments soon 😇

**Comment by rgaiacs** [comment]
Looks really awesome your post. I'm closing this for now. If you want I can have another look when you open the PR to RSE-Shefield.

**Comment by annakrystalli** [comment]
PR sent already. Got some feedback from @tdjames1 too. Thanks both for your inputs 😃
